[deps]
aiohttp = "==3.7.4"
async-timeout = "==3.0.1"
beautifulsoup4 = ""
boto3 = "=1.17.21"
dandi = ""
fsspec = ""
h5py = ""
hdmf = "=3.5.5"
meson = ""
pygments = ">=2.4.1"
pynwb = "2.3.1"
pytables = ""
python = "=3.9"
requests = ""
scikit-image = ""
statsmodels = "<=0.13.0"


