[deps]
python = "==3.10"

[pip.deps]
dandi = ""
patsy = ">=0.5.2"
pandas = ">=0.25"
statsmodels = ""
etelemetry = ">=0.2.2"
pynwb = ""
allensdk = "@https://github.com/brendanjohnharris/AllenSDK/archive/refs/tags/v2.16.zip"
numpy = ">=1.17"
scipy = ">=1.3"
boto3 = "==1.24"
tqdm = ">=4.64.1"
pydantic = ">=1.10.2"
pygments = ">=2.4.1"
beautifulsoup4 = ""
psutil = ""
