[deps]
dandi = ""
aiohttp = ""
h5py = ""
fsspec = ""
requests = ""
boto3 = "=1.17.21"
hdmf = "=3.4.7"
statsmodels = "<=0.13.0"
pynwb = "2.3.1"
beautifulsoup4 = ""
pygments = ">=2.4.1"
python = "=3.9"
meson = ""

[pip.deps]
psycopg2-binary = "==2.9.5"
allensdk = "@https://github.com/brendanjohnharris/AllenSDK/archive/refs/tags/v2.19.zip"