[deps]
boto3 = "=1.17.21"
meson = ""
statsmodels = "<=0.13.0"
pytables = ""
dandi = ""
pygments = ">=2.4.1"
psycopg2 = ""
pynwb = "2.3.1"
fsspec = ""
beautifulsoup4 = ""
h5py = ""
python = "=3.9"
hdmf = "=3.4.7"
requests = ""
scikit-image = ""

[pip.deps]
allensdk = "@https://github.com/brendanjohnharris/AllenSDK/archive/refs/tags/v2.19.zip"

