[deps]
aiohttp = ""
beautifulsoup4 = ""
boto3 = "=1.17.21"
dandi = ""
fsspec = ""
h5py = ""
hdmf = "=3.4.7"
meson = ""
pygments = ">=2.4.1"
pynwb = "2.3.1"
pytables = ""
python = "=3.9"
requests = ""
scikit-image = ""
statsmodels = "<=0.13.0"

[pip.deps]
allensdk = "@https://github.com/brendanjohnharris/AllenSDK/archive/refs/tags/v2.19.zip"

